### ISSUE TITLE
Integrate AWS SQS

### ISSUE THREAD

**Issue by harti2006** [zalando-zmon/zmon-aws-agent#98]
Our team is using AWS SQS (Simple Queue Service) a lot. For monitoring we were relying on manually created entities, but this is getting tedious and error prone.

The ZMON AWS Agent should automatically pick up all SQS queues and create entities for each of it. 

## Implementation Strategy

The idea would be to invoke [list-queues](https://boto3.readthedocs.io/en/latest/reference/services/sqs.html#SQS.Client.list_queues) and then for each entry in the array of queue urls, invoke [get_queue_attributes](https://boto3.readthedocs.io/en/latest/reference/services/sqs.html#SQS.Client.get_queue_attributes) to retrieve the settings.

## Entity Structure Proposal

```yaml
id: "sqs-<name-of-the-queue>[aws:111122223333]"
type: "aws_sqs"
name: "<name-of-the-queue>"
infrastructure_account: "aws:111122223333"
region: "eu-central-1"
url: "https://sqs.eu-central-1.amazonaws.com/111122223333/<name-of-the-queue>"
arn: "arn:aws:sqs:eu-central-1:111122223333:<name-of-the-queue>"
message_retention_period_seconds: 1209600
maximum_message_size_bytes: 262144
receive_messages_wait_time_seconds: 10
delay_seconds: 0
visibility_timeout_seconds: 30
```
